### ISSUE TITLE
QuickStart: Top Sites panel

### ISSUE THREAD

**Issue by ear1grey** [ear1grey/structured-start-tab#117]
There's a chrome API for the user's most vistied sites: [chrome.topSites](https://developer.chrome.com/docs/extensions/reference/topSites/).

This could be used to create a dynamic panel of current top sites, or used at first launch to optionally populate a panel with the users' most visited sites.

Cross Plaform question: Does Firefox have a similar API?

**Comment by toto101230** [comment]
Only chrome, edge, firefox and opera have this API
