### ISSUE TITLE
Can't rename panel

### ISSUE THREAD

**Issue by TxJson** [ear1grey/structured-start-tab#134]
It currently does not work to rename panels as they revert back once a new tab is loaded.
Version: v.1.7.0

Renamed as can be seen below:
![image](https://user-images.githubusercontent.com/16917393/115866043-0c33b480-a431-11eb-8b00-30e0e9b1dbfe.png)

When new tab is loaded:
![image](https://user-images.githubusercontent.com/16917393/115866095-1ce42a80-a431-11eb-9d0b-9d03ec824663.png)

**Comment by toto101230** [comment]
This bug has already been fixed in pull request #129

**Comment by ear1grey** [comment]
The fix will be in 1.8.0 or if you want it sooner, clone the repo.  The current master branch is good.
