### ISSUE TITLE
Migrate to Manifest V3

### ISSUE THREAD

**Issue by ear1grey** [ear1grey/structured-start-tab#182]
https://developer.chrome.com/blog/mv2-transition/

**Comment by ear1grey** [comment]
See also: https://developer.chrome.com/docs/extensions/mv3/mv3-migration/

**Comment by ear1grey** [comment]
Labelled as a 1.10 milestone as it's a significant change.

**Comment by adrianoBP** [comment]
Important note: this will most likely cause incompatibility with Firefox as many features implemented by Chrome in MV3 are not supported or have been implemented differently in Firefox.

The extension will need to be ported to Firefox ([migration guide](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/)).
