### ISSUE TITLE
preformatted text in the label

### ISSUE THREAD

**Issue by jacekkopecky** [ear1grey/structured-start-tab#243]
I wish to have a multi-line label, like this:
```
 oOo 
oOXOo 
 oOo 
```

Before the beta, I put `white-space: pre-line` in the style attribute and included newlines in the label text. In the beta, the text looks like this: " oOo oOXOo oOo "

**Comment by adrianoBP** [comment]
**Possible solution**: allow to switch between `<input>` or `<textarea>`

**Comment by jacekkopecky** [comment]
sounds like that could work; a little checkbox labeled "multi-line" that triggers the switch?

**Comment by adrianoBP** [comment]
Potentially yes, but yet to be confirmed. For consistency, we may have it as a switch similar to how the colour switch or panel direction works.

I will pick this up again when working on #240.
