### ISSUE TITLE
can't turn off options

### ISSUE THREAD

**Issue by jacekkopecky** [ear1grey/structured-start-tab#246]
ctrl-shift-b doesn't remove the options pane on the right...

**Comment by adrianoBP** [comment]
@jacekkopecky can't replicate on my end - were the keyboard shortcuts re-configured?

**Comment by adrianoBP** [comment]
Keyboard shortcuts that have already been assigned to another extension or browser's default shortcuts (e.g. `CTRL + Shift + B`) are not automatically assigned to the extension upon installation; instead, they will have to be manually configured.

**Comment by jacekkopecky** [comment]
But then the extension shouldn't tell me that I can press ctrl-shift-b to toggle the sidebar when it's not true. Right?

**Comment by adrianoBP** [comment]
Correct - I will look into that as a separate issue 🙂
