### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by ear1grey** [ear1grey/structured-start-tab#45]
Move from custom favicons to cached ones...
e.g. use `chrome://favicon/http://github.com`

**Comment by ear1grey** [comment]
Using an image that's not cached results in a broken image icon.
Fetch can't be used to check if it's a 404...
```
const imgurl = "chrome://favicon/"+link.dataset.href;
let img = await fetch(imgurl);
if (img.ok) {. ...
```
... because the `Fetch API cannot load chrome://favicon/http://example.org. URL scheme must be "http" or "https" for CORS request.`

... it could have been so simple.

**Comment by jacekkopecky** [comment]
doesn't image have `onerror` or somesuch?

**Comment by jacekkopecky** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror
