### ISSUE TITLE
Tab object duplication

### ISSUE THREAD

**Issue by TxJson** [ear1grey/structured-start-tab#48]
Every time CTRL+Z is pressed, multiple copies of the removed object get returned. Is this desired behaviour?
(Look at attached picture)
![Screenshot from 2020-07-03 10-45-11](https://user-images.githubusercontent.com/16917393/86456677-5882fc00-bd1a-11ea-8565-a6612b8a6cd3.png)

**Comment by ear1grey** [comment]
Reproducible, thanks.
