### ISSUE TITLE
Multi-level toast

### ISSUE THREAD

**Issue by ear1grey** [ear1grey/structured-start-tab#59]
Introduce two levels of toast:

- L0 = Feedback - would only be for reporting actions that have succeeded/failed. 
- L1 = Help/Tips - could be disabled for users who don't need it.

Maybe allow different levels to be different colours.

**Comment by jacekkopecky** [comment]
tips want to be close to the thing they're tipping; it's strange that the addition buttons don't have tooltips; success toasts can go away, failures sometimes want to be manually acknowledged/dismissed
