### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by ear1grey** [ear1grey/structured-start-tab#75]
The contet menu should:
- [x] Mirror the content of the sidebar, including
   - [x] Add link, which adds a link at the current target 
   - [x] Add panel, which adds a link at the current target
   - [x] Move to trash (the current link, panel)
- [x] Lock [on/off]
- [x] Show sidebar [on/off]
- [x] Options
- [x] Empty Trash

**Comment by jacekkopecky** [comment]
empty trash isn't working
