### ISSUE TITLE
Add docs for configuring sidebar toggle key (⌘B)

### ISSUE THREAD

**Issue by ear1grey** [ear1grey/structured-start-tab#76]

**Comment by jacekkopecky** [comment]
chrome makes it configurable under chrome://extensions -> hamburger menu (top-left) -> keyboard shortcuts; this issue should be to point this out in the docs somewhere

**Comment by ear1grey** [comment]
This will be 'interesting' because different browsers do it in different ways. 
_Perhaps_ linking to a guide by each vendor is the right approach.
