### ISSUE TITLE
Options page Issues 

### ISSUE THREAD

**Issue by TLDRQwerty** [ear1grey/structured-start-tab#90]
On firefox the option `Space between items.` updates the spaces between the options themselves. (On chrome edge this doesn't happen) This makes it hard to change options this slows down the page and makes it hard to change the option. A solution to this would be updating at the end of the drag event.

Both the `Space between items.` and `Adjust font size.` are slow to update and lag behind the user input if changed really fast. (Firefox temporary extension).

**Comment by ear1grey** [comment]
Options page spacing should probbaly not be affected by the spacing for the main page.
I've previously thought of block of dummy links in the layout section would immediately illustrate each of the options.
