### ISSUE TITLE
on locked page, (un-)collapsing sections should be saved

### ISSUE THREAD

**Issue by jacekkopecky** [ear1grey/structured-start-tab#97]
A locked page allows me to collapse a section, or open a collapsed section, which is good, but these changes shouldn't be saved I think.

**Comment by ear1grey** [comment]
Should this be an option, or maybe two options?
1. Allow collapsing and opening of panels when page is locked [ ], and
2. Remember status of panel (open/collapsed) if it changes when the page is locked [ ]
